// Финальные PNG-дизайны пинов (512×512). Ключ — icon_slug ачивки.
// Источник — генерации после removebg, вписаны в квадрат 512² с прозрачным паддингом.
// Показываются ТОЛЬКО для открытых ачивок (см. AchievementPin.pickAsset).
import type { ImageSourcePropType } from 'react-native';

export const DESIGN_PNGS: Record<string, ImageSourcePropType> = {
  a1_first_record: require('./a1_first_record.png'),
  a2_first_wishlist: require('./a2_first_wishlist.png'),
  a3_avatar: require('./a3_avatar.png'),
  a4_public_profile: require('./a4_public_profile.png'),
  b1_starter: require('./b1_starter.png'),
  b2_collector: require('./b2_collector.png'),
  b3_archivist: require('./b3_archivist.png'),
  b4_curator: require('./b4_curator.png'),
  b5_keeper: require('./b5_keeper.png'),
  c2_limited_x25: require('./c2_limited_x25.png'),
  c3_collectible_x1: require('./c3_collectible_x1.png'),
  c5_collectible_x15: require('./c5_collectible_x15.png'),
  c6_hot_in_wishlist: require('./c6_hot_in_wishlist.png'),
  d3_country_x30: require('./d3_country_x30.png'),
  d4_japanese_x10: require('./d4_japanese_x10.png'),
  d5_melodiya_x10: require('./d5_melodiya_x10.png'),
  d6_uk_collectible_x3: require('./d6_uk_collectible_x3.png'),
  e1_60s: require('./e1_60s.png'),
  e2_70s: require('./e2_70s.png'),
  e3_80s: require('./e3_80s.png'),
  e4_modern: require('./e4_modern.png'),
  e5_pre_1960: require('./e5_pre_1960.png'),
  f2_diversity_10: require('./f2_diversity_10.png'),
  f3_jazz_x25: require('./f3_jazz_x25.png'),
  f4_electronic_x25: require('./f4_electronic_x25.png'),
  h1_artist_x5: require('./h1_artist_x5.png'),
  h2_artist_studio_full: require('./h2_artist_studio_full.png'),
  h3_master_pressings_3: require('./h3_master_pressings_3.png'),
  h4_master_pressings_5: require('./h4_master_pressings_5.png'),
  h5_label_x20: require('./h5_label_x20.png'),
  j1_first_gift: require('./j1_first_gift.png'),
  j2_gift_done: require('./j2_gift_done.png'),
  j3_three_recipients: require('./j3_three_recipients.png'),
  k1_following_x5: require('./k1_following_x5.png'),
  k2_first_follower: require('./k2_first_follower.png'),
  k3_followers_x5: require('./k3_followers_x5.png'),
  k4_followers_x50: require('./k4_followers_x50.png'),
  k7_mutual_x10: require('./k7_mutual_x10.png'),
  k8_contrib_x1: require('./k8_contrib_x1.png'),
  k9_contrib_x5: require('./k9_contrib_x5.png'),
  k10_contrib_x20: require('./k10_contrib_x20.png'),
  k11_msgs_x10: require('./k11_msgs_x10.png'),
  k12_msgs_x50: require('./k12_msgs_x50.png'),
  k13_msgs_x200: require('./k13_msgs_x200.png'),
  k14_wanted_x1: require('./k14_wanted_x1.png'),
  k15_wanted_x5: require('./k15_wanted_x5.png'),
  k16_wanted_x10: require('./k16_wanted_x10.png'),
  m1_first_drawer: require('./m1_first_drawer.png'),
  m2_first_click: require('./m2_first_click.png'),
  m3_wishlist_hunter: require('./m3_wishlist_hunter.png'),
  m4_deal_finder: require('./m4_deal_finder.png'),
  m5_regular: require('./m5_regular.png'),
  meta_community: require('./meta_community.png'),
  meta_depth: require('./meta_depth.png'),
  meta_market: require('./meta_market.png'),
  mv1_appraised: require('./mv1_appraised.png'),
  mv2_50k: require('./mv2_50k.png'),
  mv3_100k: require('./mv3_100k.png'),
  mv4_250k: require('./mv4_250k.png'),
  mv5_500k: require('./mv5_500k.png'),
  mv6_million: require('./mv6_million.png'),
  meta_foundation: require('./meta_foundation.png'),
  meta_scale: require('./meta_scale.png'),
  r_self_titled: require('./r_self_titled.png'),
  r_thirty_three: require('./r_thirty_three.png'),
};
